Solve issues
dclimber/python-exchangeratesapi pull request #6
Opened 2021-04-12 09:38 UTC by bizzyvinci

As mentioned in issue #5, API_KEY is now required by [exchangeratesapi](https://exchangeratesapi.io/). It's quite surprising cause I used the API a few weeks. But by reading the [documentation](https://exchangeratesapi.io/documentation), I discovered there's more to it including changes to endpoints and params. The old documentation for comparison is [this](https://web.archive.org/web/20210328014153/http://exchangeratesapi.io/).

**This pull request should not be merged cause there seems to be a lot to do including changing the tests.** I'm submitting so it can be reviewed and I can get comments.

Done:
- [x] issue #5 in the first commit
- [x] Change base url from https://api.exchangeratesapi.io to https://api.exchangeratesapi.io/v1
- [x] issue #4 by creating a class ExchangeRatesApiException and _get_error_message method
- [x] update endpoints and params

There are only 250 requests for free tier of the API, so I plan to optimize that :grin:. Therefore, the changes have not been tested yet.

To Do:
- [ ] Work on other endpoints (probably)
- [ ] Resolve issue #3 by using symbols endpoint (or another way)
- [ ] Update tests

Ahahahahah. I just understand issue #2. I'll change `date` to `start_date` right away.

2021-04-12 11:09 UTC, dk-WZFinTech requested changes
You are missing the update of test case here: https://github.com/dclimber/python-exchangeratesapi/blob/master/test/test_api.py

2021-04-12 11:09 UTC, dk-WZFinTech commented on exchangeratesapi/api.py
> +        #'history': 'history',
Remove this commented code.

2021-04-12 11:09 UTC, dk-WZFinTech commented on exchangeratesapi/api.py
> +    def __init__(self, API_KEY):
use lower-key here: `API_KEY` -> `api_key`

2021-04-13 07:50 UTC, dk-WZFinTech requested changes
To accept this changes please adapt test cases file.

2021-04-13 07:50 UTC, dk-WZFinTech commented on exchangeratesapi/api.py
> +    def _get_error_message(self, error):
If you are not using `self` then this mean this is staticmethod:

```suggestion
    @staticmethod
    def _get_error_message(error):
```

2021-04-13 08:04 UTC, dk-WZFinTech commented
Also it will be good to mention in `README` file about required parameter `API_KEY`

2021-04-13 09:00 UTC, bizzyvinci commented
Thanks a lot @dk-WZFinTech for your comments and suggestions.

I'll update README as soon as possible.

I've started working on tests with a free tier key but the 2 challenges are:
1. The free tier does not use secured `https`, therefore base_url must be `http://api.exchangeratesapi.io/v1/` else an error message would be raised in init.
2. There's no access to other endpoints including `timeseries` which was formerly `history`. Only symbols, latest and historical are available to me.

I've looked at the pricing table and each higher tier adds just one more endpoints. Therefore, I'll need different tier account or the highest tier to test all cases and endpoints. Here's what I plan to do for that.
1. I'll see if I can message exchangeratesapi and request for a specialized key with limited api calls but access to all endpoints and use for testing.
OR
2. Remove timeseries and other endpoints, and make the library only for free tier accounts.

2021-04-13 11:57 UTC, bizzyvinci commented
README and Tests has been updated. But tests for _get_url and _get_error_message methods has not been included YET.

Using a free api key, there are 6 failures because of endpoint timeseries or params base restriction.

One notable failure was `test_get_rate_targ_one_date - assert 0.83153 == 0.8336`. From the api `eur_to_gbp on start_date==0.8315` while `eur_to_gbp on next_date==0.8275` both of which is not equal to `eur_to_gbp_next_date=0.8336`. So I'll make change to that in following commits.

2021-04-14 07:16 UTC, dk-WZFinTech commented
> One notable failure was `test_get_rate_targ_one_date - assert 0.83153 == 0.8336`. From the api `eur_to_gbp on start_date==0.8315` while `eur_to_gbp on next_date==0.8275` both of which is not equal to `eur_to_gbp_next_date=0.8336`. So I'll make change to that in following commits.

This is because looks like they replaced DB with different one.

2021-04-14 08:07 UTC, dk-WZFinTech reviewed
> Using a free api key, there are 6 failures because of endpoint timeseries or params base restriction.

For those please use pytest decorator [xfail](https://docs.pytest.org/en/reorganize-docs/new-docs/user/xfail.html)

2021-04-14 08:07 UTC, dk-WZFinTech commented on exchangeratesapi/api.py
> +    API_URL = 'http://api.exchangeratesapi.io/v1/{endpoint}{params}'
IMO we should give developer opportunity to use both protocols. For that you can use environment variables.

```py

API_ENDPOINT = os.getenv('EXCHANGE_API_ENDPOINT', 'http://api.exchangeratesapi.io/v1/')
```

so then:

```py

class Api(object):
    API_URL = API_ENDPOINT + '{endpoint}{params}'
```

2021-04-14 08:07 UTC, dk-WZFinTech commented on exchangeratesapi/api.py
> +    def __init__(self, api_key):
Similar as I commented here: https://github.com/dclimber/python-exchangeratesapi/pull/6/files#diff-3fe831c65f29cffa2ca1fde993d6ac83ddf4caad694b61a5fbd3dead00e0814bR11

you can also set default `api_key`:

```py
    API_KEY = os.getenv('EXCHANGE_API')  # if not set will return `None`

    def __init__(self, api_key=API_KEY):
         if not api_key:
              raise ExchangeRatesApiException(
                      'Exchange rate API KEY is missing.'
              )
              ...
```

But this is only suggestion :)

2021-04-14 08:07 UTC, dk-WZFinTech commented on test/conftest.py
> +def old_supported_currencies():
I think we can remove this -> cause it is not used anywhere

2021-04-14 08:07 UTC, dk-WZFinTech commented on test/test_api.py
> +access_key = os.environ['EXCHANGERATESAPI_FREE_KEY']
As I wrote above - we can set default.

2021-04-14 08:09 UTC, dk-WZFinTech reviewed
Overall looks really nice.

Just some suggestion to improvement.

About test case I am happy that you update them. When I will have a time I will check those that fail with our paid key -> for now you can create issue if you cannot check them by you.

And I am waiting for those:

> But tests for _get_url and _get_error_message methods has not been included YET

2021-04-14 11:05 UTC, bizzyvinci commented
Thanks. I've received a Business key from exchangeratesapi. This would enable me to add other endpoints and perform full test.

I'll review all your suggestions in following developments.

2021-04-14 12:44 UTC, bizzyvinci commented on exchangeratesapi/api.py
> +    API_URL = 'http://api.exchangeratesapi.io/v1/{endpoint}{params}'
Another way is to know if a provided access key **cannot** use secured layer and then replace https with http in self.API_URL in the _get_symbols method.

2021-04-14 12:45 UTC, bizzyvinci commented on exchangeratesapi/api.py
> +    def __init__(self, api_key):
Nice suggestion, I'll add that.

2021-04-14 12:51 UTC, bizzyvinci commented on test/conftest.py
> +def old_supported_currencies():
Thanks, I've removed old_supported_currencies in this [commit](https://github.com/dclimber/python-exchangeratesapi/pull/6/commits/4a2b8173bdb379a9ea19fff83ad8d80e30c15955)

2021-04-14 13:10 UTC, bizzyvinci commented on exchangeratesapi/api.py
> +    def __init__(self, api_key):
Done at https://github.com/dclimber/python-exchangeratesapi/pull/6/commits/683210297567b3946a16f4f5030dd6ffdf6ffded

2021-04-15 19:34 UTC, dk-WZFinTech commented
Hi @bizzyvinci 
I really like your work here :1st_place_medal: .

Unfortunately today I didn't have a time to review new code.

Tomorrow if I finished all my work I will try to come back here :) and review it.

I hope @dclimber will have time to also check this code out and after acceptance merge your PR - nevertheless we will somehow figure it out.

2021-04-19 15:02 UTC, dclimber commented
Hey guys, sorry for the wait. I was busy.
I'll take a look at the PR tomorrow or on Wednesday.

2021-05-13 21:18 UTC, closed without merging